### ISSUE TITLE
Unraid?

### ISSUE THREAD

**Issue by Tharic99** [haijeploeg/exclude_streaming_radarr#1]
Just a quick question on any recommendations for using this under Unraid? Not sure what you're base OS is, so I figured I'd throw this out there.

I know it's possible using the Unraid User Scripts plugin, but I wasn't sure if you had experience with that or not.

Thanks and great work on the script!

**Comment by haijeploeg** [comment]
Hi Tharic99,

Thank you! I use MacOS and ubuntu 18.04/20.04 mainly for development. I don't have any experience with unraid actually. But it is on my list to add a Docker container for this as well. I see that unraid does support Docker, so maybe that will be a solution for you in the future?

**Comment by Tharic99** [comment]
I actually got it working with the Unraid User Scripts, so it will work under Unraid.

For anyone else who comes here.

Make sure you have the User Scripts and the Nerd Tools addons installed.

Create a folder in your Appdata folder for this and extract the download zip into that folder. 

Modify the `exclude_streaming_from_radarr.py` file per the instructions.

Open up a Terminal Prompt in the Unraid console and navigate to the folder you created under appdata for this.

Run a `pip3 install -requirements.txt` from the command line terminal to make sure you have all the requirements in place.

Then from the terminal, you can execute a `python3 exclude_streaming_from_radarr.py` to actually run the script

**Comment by haijeploeg** [comment]
Hi Tharic99,

Great that you have figured it out. If it is okay with you I will add this to the Readme file.

**Comment by Tharic99** [comment]
Sure thing. Feel free to clean it up so it flows better/etc as well!

**Comment by jokerigno** [comment]
HI @Tharic99 file exclude_streaming_from_radarr.py no longer exist. Can you please help me to run it (via script or via docker) in my Unraid Server?
